services:
  database:
    image: gvenzl/oracle-xe:latest
    container_name: oracle_bodega
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=tu_password_segura
      - APP_USER=BODEGA_USER
      - APP_USER_PASSWORD=bodega_pass
    volumes:
      - ./database/init.sql:/container-entrypoint-initdb.d/init.sql:ro
    restart: always

  
  api:
    image: node:20-alpine
    container_name: api_bodega
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
     
      - DB_USER=BODEGA_USER
      - DB_PASSWORD=bodega_pass

      - DB_CONNECTION_STRING=database:1521/XEPDB1
    command: sh -c "npm install && node server.js"
    depends_on:
      - database

  web:
    image: nginx:alpine
    container_name: web_bodega
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
    depends_on:
      - api